### ISSUE TITLE
KeyError: 'getpwuid(): uid not found

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/dashboard#9]
If a user has been removed to `/etc/passwd`, the following error happens:
```bash
Traceback (most recent call last):
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/data/pnl/soft/pnlpipe3/dashboard/scripts/dashboard.py", line 3, in <module>
    import pandas as pd
  File "/data/pnl/soft/pnlpipe3/dashboard/scripts/dashboard.py", line 169, in generateReport
    df = getDetails(cases, item)
  File "/data/pnl/soft/pnlpipe3/dashboard/scripts/dashboard.py", line 71, in getDetails
    details.loc[row] = [id, basename(target), getpwuid(stat_obj.st_uid).pw_name,
KeyError: 'getpwuid(): uid not found: 4430684'
```

**Comment by tashrifbillah** [comment]
**ENH**
In future, we can also print just `stat_obj.st_uid`. The latter is a number which will not be meaningful to report readers anyway. So skipping the removed users for now.
